// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package net.arksea.dsf.demo;

public final class DEMO {
  private DEMO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoRequest1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.arksea.dsf.demo.DemoRequest1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>int32 consistentHashKey = 2;</code>
     */
    int getConsistentHashKey();

    /**
     * <code>bytes tracingSpan = 3;</code>
     */
    com.google.protobuf.ByteString getTracingSpan();
  }
  /**
   * Protobuf type {@code net.arksea.dsf.demo.DemoRequest1}
   */
  public  static final class DemoRequest1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.arksea.dsf.demo.DemoRequest1)
      DemoRequest1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DemoRequest1.newBuilder() to construct.
    private DemoRequest1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoRequest1() {
      msg_ = "";
      consistentHashKey_ = 0;
      tracingSpan_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemoRequest1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 16: {

              consistentHashKey_ = input.readInt32();
              break;
            }
            case 26: {

              tracingSpan_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoRequest1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoRequest1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.arksea.dsf.demo.DEMO.DemoRequest1.class, net.arksea.dsf.demo.DEMO.DemoRequest1.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSISTENTHASHKEY_FIELD_NUMBER = 2;
    private int consistentHashKey_;
    /**
     * <code>int32 consistentHashKey = 2;</code>
     */
    public int getConsistentHashKey() {
      return consistentHashKey_;
    }

    public static final int TRACINGSPAN_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString tracingSpan_;
    /**
     * <code>bytes tracingSpan = 3;</code>
     */
    public com.google.protobuf.ByteString getTracingSpan() {
      return tracingSpan_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
      }
      if (consistentHashKey_ != 0) {
        output.writeInt32(2, consistentHashKey_);
      }
      if (!tracingSpan_.isEmpty()) {
        output.writeBytes(3, tracingSpan_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
      }
      if (consistentHashKey_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, consistentHashKey_);
      }
      if (!tracingSpan_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, tracingSpan_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.arksea.dsf.demo.DEMO.DemoRequest1)) {
        return super.equals(obj);
      }
      net.arksea.dsf.demo.DEMO.DemoRequest1 other = (net.arksea.dsf.demo.DEMO.DemoRequest1) obj;

      boolean result = true;
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (getConsistentHashKey()
          == other.getConsistentHashKey());
      result = result && getTracingSpan()
          .equals(other.getTracingSpan());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + CONSISTENTHASHKEY_FIELD_NUMBER;
      hash = (53 * hash) + getConsistentHashKey();
      hash = (37 * hash) + TRACINGSPAN_FIELD_NUMBER;
      hash = (53 * hash) + getTracingSpan().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DemoRequest1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.arksea.dsf.demo.DEMO.DemoRequest1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.arksea.dsf.demo.DemoRequest1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.arksea.dsf.demo.DemoRequest1)
        net.arksea.dsf.demo.DEMO.DemoRequest1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoRequest1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoRequest1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.arksea.dsf.demo.DEMO.DemoRequest1.class, net.arksea.dsf.demo.DEMO.DemoRequest1.Builder.class);
      }

      // Construct using net.arksea.dsf.demo.DEMO.DemoRequest1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msg_ = "";

        consistentHashKey_ = 0;

        tracingSpan_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoRequest1_descriptor;
      }

      public net.arksea.dsf.demo.DEMO.DemoRequest1 getDefaultInstanceForType() {
        return net.arksea.dsf.demo.DEMO.DemoRequest1.getDefaultInstance();
      }

      public net.arksea.dsf.demo.DEMO.DemoRequest1 build() {
        net.arksea.dsf.demo.DEMO.DemoRequest1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.arksea.dsf.demo.DEMO.DemoRequest1 buildPartial() {
        net.arksea.dsf.demo.DEMO.DemoRequest1 result = new net.arksea.dsf.demo.DEMO.DemoRequest1(this);
        result.msg_ = msg_;
        result.consistentHashKey_ = consistentHashKey_;
        result.tracingSpan_ = tracingSpan_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.arksea.dsf.demo.DEMO.DemoRequest1) {
          return mergeFrom((net.arksea.dsf.demo.DEMO.DemoRequest1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.arksea.dsf.demo.DEMO.DemoRequest1 other) {
        if (other == net.arksea.dsf.demo.DEMO.DemoRequest1.getDefaultInstance()) return this;
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getConsistentHashKey() != 0) {
          setConsistentHashKey(other.getConsistentHashKey());
        }
        if (other.getTracingSpan() != com.google.protobuf.ByteString.EMPTY) {
          setTracingSpan(other.getTracingSpan());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.arksea.dsf.demo.DEMO.DemoRequest1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.arksea.dsf.demo.DEMO.DemoRequest1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int consistentHashKey_ ;
      /**
       * <code>int32 consistentHashKey = 2;</code>
       */
      public int getConsistentHashKey() {
        return consistentHashKey_;
      }
      /**
       * <code>int32 consistentHashKey = 2;</code>
       */
      public Builder setConsistentHashKey(int value) {
        
        consistentHashKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 consistentHashKey = 2;</code>
       */
      public Builder clearConsistentHashKey() {
        
        consistentHashKey_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString tracingSpan_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes tracingSpan = 3;</code>
       */
      public com.google.protobuf.ByteString getTracingSpan() {
        return tracingSpan_;
      }
      /**
       * <code>bytes tracingSpan = 3;</code>
       */
      public Builder setTracingSpan(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tracingSpan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes tracingSpan = 3;</code>
       */
      public Builder clearTracingSpan() {
        
        tracingSpan_ = getDefaultInstance().getTracingSpan();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.arksea.dsf.demo.DemoRequest1)
    }

    // @@protoc_insertion_point(class_scope:net.arksea.dsf.demo.DemoRequest1)
    private static final net.arksea.dsf.demo.DEMO.DemoRequest1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.arksea.dsf.demo.DEMO.DemoRequest1();
    }

    public static net.arksea.dsf.demo.DEMO.DemoRequest1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DemoRequest1>
        PARSER = new com.google.protobuf.AbstractParser<DemoRequest1>() {
      public DemoRequest1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DemoRequest1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoRequest1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoRequest1> getParserForType() {
      return PARSER;
    }

    public net.arksea.dsf.demo.DEMO.DemoRequest1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DemoResponse1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.arksea.dsf.demo.DemoResponse1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>int32 status = 2;</code>
     */
    int getStatus();

    /**
     * <code>bytes tracingSpan = 3;</code>
     */
    com.google.protobuf.ByteString getTracingSpan();
  }
  /**
   * Protobuf type {@code net.arksea.dsf.demo.DemoResponse1}
   */
  public  static final class DemoResponse1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.arksea.dsf.demo.DemoResponse1)
      DemoResponse1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DemoResponse1.newBuilder() to construct.
    private DemoResponse1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoResponse1() {
      msg_ = "";
      status_ = 0;
      tracingSpan_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemoResponse1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 16: {

              status_ = input.readInt32();
              break;
            }
            case 26: {

              tracingSpan_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoResponse1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoResponse1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.arksea.dsf.demo.DEMO.DemoResponse1.class, net.arksea.dsf.demo.DEMO.DemoResponse1.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>int32 status = 2;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int TRACINGSPAN_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString tracingSpan_;
    /**
     * <code>bytes tracingSpan = 3;</code>
     */
    public com.google.protobuf.ByteString getTracingSpan() {
      return tracingSpan_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
      }
      if (status_ != 0) {
        output.writeInt32(2, status_);
      }
      if (!tracingSpan_.isEmpty()) {
        output.writeBytes(3, tracingSpan_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (!tracingSpan_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, tracingSpan_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.arksea.dsf.demo.DEMO.DemoResponse1)) {
        return super.equals(obj);
      }
      net.arksea.dsf.demo.DEMO.DemoResponse1 other = (net.arksea.dsf.demo.DEMO.DemoResponse1) obj;

      boolean result = true;
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (getStatus()
          == other.getStatus());
      result = result && getTracingSpan()
          .equals(other.getTracingSpan());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + TRACINGSPAN_FIELD_NUMBER;
      hash = (53 * hash) + getTracingSpan().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DemoResponse1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.arksea.dsf.demo.DEMO.DemoResponse1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.arksea.dsf.demo.DemoResponse1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.arksea.dsf.demo.DemoResponse1)
        net.arksea.dsf.demo.DEMO.DemoResponse1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoResponse1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoResponse1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.arksea.dsf.demo.DEMO.DemoResponse1.class, net.arksea.dsf.demo.DEMO.DemoResponse1.Builder.class);
      }

      // Construct using net.arksea.dsf.demo.DEMO.DemoResponse1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msg_ = "";

        status_ = 0;

        tracingSpan_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DemoResponse1_descriptor;
      }

      public net.arksea.dsf.demo.DEMO.DemoResponse1 getDefaultInstanceForType() {
        return net.arksea.dsf.demo.DEMO.DemoResponse1.getDefaultInstance();
      }

      public net.arksea.dsf.demo.DEMO.DemoResponse1 build() {
        net.arksea.dsf.demo.DEMO.DemoResponse1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.arksea.dsf.demo.DEMO.DemoResponse1 buildPartial() {
        net.arksea.dsf.demo.DEMO.DemoResponse1 result = new net.arksea.dsf.demo.DEMO.DemoResponse1(this);
        result.msg_ = msg_;
        result.status_ = status_;
        result.tracingSpan_ = tracingSpan_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.arksea.dsf.demo.DEMO.DemoResponse1) {
          return mergeFrom((net.arksea.dsf.demo.DEMO.DemoResponse1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.arksea.dsf.demo.DEMO.DemoResponse1 other) {
        if (other == net.arksea.dsf.demo.DEMO.DemoResponse1.getDefaultInstance()) return this;
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getTracingSpan() != com.google.protobuf.ByteString.EMPTY) {
          setTracingSpan(other.getTracingSpan());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.arksea.dsf.demo.DEMO.DemoResponse1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.arksea.dsf.demo.DEMO.DemoResponse1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 2;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString tracingSpan_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes tracingSpan = 3;</code>
       */
      public com.google.protobuf.ByteString getTracingSpan() {
        return tracingSpan_;
      }
      /**
       * <code>bytes tracingSpan = 3;</code>
       */
      public Builder setTracingSpan(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tracingSpan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes tracingSpan = 3;</code>
       */
      public Builder clearTracingSpan() {
        
        tracingSpan_ = getDefaultInstance().getTracingSpan();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.arksea.dsf.demo.DemoResponse1)
    }

    // @@protoc_insertion_point(class_scope:net.arksea.dsf.demo.DemoResponse1)
    private static final net.arksea.dsf.demo.DEMO.DemoResponse1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.arksea.dsf.demo.DEMO.DemoResponse1();
    }

    public static net.arksea.dsf.demo.DEMO.DemoResponse1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DemoResponse1>
        PARSER = new com.google.protobuf.AbstractParser<DemoResponse1>() {
      public DemoResponse1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DemoResponse1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoResponse1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoResponse1> getParserForType() {
      return PARSER;
    }

    public net.arksea.dsf.demo.DEMO.DemoResponse1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.arksea.dsf.demo.DataResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>int32 serialize = 3;</code>
     */
    int getSerialize();

    /**
     * <code>string typeName = 4;</code>
     */
    java.lang.String getTypeName();
    /**
     * <code>string typeName = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeNameBytes();

    /**
     * <code>int64 expiredTime = 5;</code>
     */
    long getExpiredTime();

    /**
     * <code>int32 errorCode = 6;</code>
     */
    int getErrorCode();

    /**
     * <code>bytes tracingSpan_ = 7;</code>
     */
    com.google.protobuf.ByteString getTracingSpan();
  }
  /**
   * Protobuf type {@code net.arksea.dsf.demo.DataResult}
   */
  public  static final class DataResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.arksea.dsf.demo.DataResult)
      DataResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataResult.newBuilder() to construct.
    private DataResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataResult() {
      key_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
      serialize_ = 0;
      typeName_ = "";
      expiredTime_ = 0L;
      errorCode_ = 0;
      tracingSpan_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
            case 24: {

              serialize_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              typeName_ = s;
              break;
            }
            case 40: {

              expiredTime_ = input.readInt64();
              break;
            }
            case 48: {

              errorCode_ = input.readInt32();
              break;
            }
            case 58: {

              tracingSpan_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DataResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DataResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.arksea.dsf.demo.DEMO.DataResult.class, net.arksea.dsf.demo.DEMO.DataResult.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int SERIALIZE_FIELD_NUMBER = 3;
    private int serialize_;
    /**
     * <code>int32 serialize = 3;</code>
     */
    public int getSerialize() {
      return serialize_;
    }

    public static final int TYPENAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object typeName_;
    /**
     * <code>string typeName = 4;</code>
     */
    public java.lang.String getTypeName() {
      java.lang.Object ref = typeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeName_ = s;
        return s;
      }
    }
    /**
     * <code>string typeName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeNameBytes() {
      java.lang.Object ref = typeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIREDTIME_FIELD_NUMBER = 5;
    private long expiredTime_;
    /**
     * <code>int64 expiredTime = 5;</code>
     */
    public long getExpiredTime() {
      return expiredTime_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 6;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 6;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int TRACINGSPAN__FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString tracingSpan_;
    /**
     * <code>bytes tracingSpan_ = 7;</code>
     */
    public com.google.protobuf.ByteString getTracingSpan() {
      return tracingSpan_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      if (serialize_ != 0) {
        output.writeInt32(3, serialize_);
      }
      if (!getTypeNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, typeName_);
      }
      if (expiredTime_ != 0L) {
        output.writeInt64(5, expiredTime_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(6, errorCode_);
      }
      if (!tracingSpan_.isEmpty()) {
        output.writeBytes(7, tracingSpan_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      if (serialize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, serialize_);
      }
      if (!getTypeNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, typeName_);
      }
      if (expiredTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, expiredTime_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, errorCode_);
      }
      if (!tracingSpan_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, tracingSpan_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.arksea.dsf.demo.DEMO.DataResult)) {
        return super.equals(obj);
      }
      net.arksea.dsf.demo.DEMO.DataResult other = (net.arksea.dsf.demo.DEMO.DataResult) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && (getSerialize()
          == other.getSerialize());
      result = result && getTypeName()
          .equals(other.getTypeName());
      result = result && (getExpiredTime()
          == other.getExpiredTime());
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && getTracingSpan()
          .equals(other.getTracingSpan());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (37 * hash) + SERIALIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSerialize();
      hash = (37 * hash) + TYPENAME_FIELD_NUMBER;
      hash = (53 * hash) + getTypeName().hashCode();
      hash = (37 * hash) + EXPIREDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpiredTime());
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (37 * hash) + TRACINGSPAN__FIELD_NUMBER;
      hash = (53 * hash) + getTracingSpan().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.arksea.dsf.demo.DEMO.DataResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.arksea.dsf.demo.DEMO.DataResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.arksea.dsf.demo.DataResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.arksea.dsf.demo.DataResult)
        net.arksea.dsf.demo.DEMO.DataResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DataResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DataResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.arksea.dsf.demo.DEMO.DataResult.class, net.arksea.dsf.demo.DEMO.DataResult.Builder.class);
      }

      // Construct using net.arksea.dsf.demo.DEMO.DataResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";

        payload_ = com.google.protobuf.ByteString.EMPTY;

        serialize_ = 0;

        typeName_ = "";

        expiredTime_ = 0L;

        errorCode_ = 0;

        tracingSpan_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.arksea.dsf.demo.DEMO.internal_static_net_arksea_dsf_demo_DataResult_descriptor;
      }

      public net.arksea.dsf.demo.DEMO.DataResult getDefaultInstanceForType() {
        return net.arksea.dsf.demo.DEMO.DataResult.getDefaultInstance();
      }

      public net.arksea.dsf.demo.DEMO.DataResult build() {
        net.arksea.dsf.demo.DEMO.DataResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.arksea.dsf.demo.DEMO.DataResult buildPartial() {
        net.arksea.dsf.demo.DEMO.DataResult result = new net.arksea.dsf.demo.DEMO.DataResult(this);
        result.key_ = key_;
        result.payload_ = payload_;
        result.serialize_ = serialize_;
        result.typeName_ = typeName_;
        result.expiredTime_ = expiredTime_;
        result.errorCode_ = errorCode_;
        result.tracingSpan_ = tracingSpan_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.arksea.dsf.demo.DEMO.DataResult) {
          return mergeFrom((net.arksea.dsf.demo.DEMO.DataResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.arksea.dsf.demo.DEMO.DataResult other) {
        if (other == net.arksea.dsf.demo.DEMO.DataResult.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        if (other.getSerialize() != 0) {
          setSerialize(other.getSerialize());
        }
        if (!other.getTypeName().isEmpty()) {
          typeName_ = other.typeName_;
          onChanged();
        }
        if (other.getExpiredTime() != 0L) {
          setExpiredTime(other.getExpiredTime());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (other.getTracingSpan() != com.google.protobuf.ByteString.EMPTY) {
          setTracingSpan(other.getTracingSpan());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.arksea.dsf.demo.DEMO.DataResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.arksea.dsf.demo.DEMO.DataResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private int serialize_ ;
      /**
       * <code>int32 serialize = 3;</code>
       */
      public int getSerialize() {
        return serialize_;
      }
      /**
       * <code>int32 serialize = 3;</code>
       */
      public Builder setSerialize(int value) {
        
        serialize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serialize = 3;</code>
       */
      public Builder clearSerialize() {
        
        serialize_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object typeName_ = "";
      /**
       * <code>string typeName = 4;</code>
       */
      public java.lang.String getTypeName() {
        java.lang.Object ref = typeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          typeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string typeName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeNameBytes() {
        java.lang.Object ref = typeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string typeName = 4;</code>
       */
      public Builder setTypeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        typeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string typeName = 4;</code>
       */
      public Builder clearTypeName() {
        
        typeName_ = getDefaultInstance().getTypeName();
        onChanged();
        return this;
      }
      /**
       * <code>string typeName = 4;</code>
       */
      public Builder setTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        typeName_ = value;
        onChanged();
        return this;
      }

      private long expiredTime_ ;
      /**
       * <code>int64 expiredTime = 5;</code>
       */
      public long getExpiredTime() {
        return expiredTime_;
      }
      /**
       * <code>int64 expiredTime = 5;</code>
       */
      public Builder setExpiredTime(long value) {
        
        expiredTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expiredTime = 5;</code>
       */
      public Builder clearExpiredTime() {
        
        expiredTime_ = 0L;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 6;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 6;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 6;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString tracingSpan_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes tracingSpan_ = 7;</code>
       */
      public com.google.protobuf.ByteString getTracingSpan() {
        return tracingSpan_;
      }
      /**
       * <code>bytes tracingSpan_ = 7;</code>
       */
      public Builder setTracingSpan(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tracingSpan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes tracingSpan_ = 7;</code>
       */
      public Builder clearTracingSpan() {
        
        tracingSpan_ = getDefaultInstance().getTracingSpan();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.arksea.dsf.demo.DataResult)
    }

    // @@protoc_insertion_point(class_scope:net.arksea.dsf.demo.DataResult)
    private static final net.arksea.dsf.demo.DEMO.DataResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.arksea.dsf.demo.DEMO.DataResult();
    }

    public static net.arksea.dsf.demo.DEMO.DataResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataResult>
        PARSER = new com.google.protobuf.AbstractParser<DataResult>() {
      public DataResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataResult> getParserForType() {
      return PARSER;
    }

    public net.arksea.dsf.demo.DEMO.DataResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_arksea_dsf_demo_DemoRequest1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_arksea_dsf_demo_DemoRequest1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_arksea_dsf_demo_DemoResponse1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_arksea_dsf_demo_DemoResponse1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_arksea_dsf_demo_DataResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_arksea_dsf_demo_DataResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nDemo.proto\022\023net.arksea.dsf.demo\"K\n\014Dem" +
      "oRequest1\022\013\n\003msg\030\001 \001(\t\022\031\n\021consistentHash" +
      "Key\030\002 \001(\005\022\023\n\013tracingSpan\030\003 \001(\014\"A\n\rDemoRe" +
      "sponse1\022\013\n\003msg\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022\023\n\013" +
      "tracingSpan\030\003 \001(\014\"\215\001\n\nDataResult\022\013\n\003key\030" +
      "\001 \001(\t\022\017\n\007payload\030\002 \001(\014\022\021\n\tserialize\030\003 \001(" +
      "\005\022\020\n\010typeName\030\004 \001(\t\022\023\n\013expiredTime\030\005 \001(\003" +
      "\022\021\n\terrorCode\030\006 \001(\005\022\024\n\014tracingSpan_\030\007 \001(" +
      "\014B\033\n\023net.arksea.dsf.demoB\004DEMOb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_arksea_dsf_demo_DemoRequest1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_arksea_dsf_demo_DemoRequest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_arksea_dsf_demo_DemoRequest1_descriptor,
        new java.lang.String[] { "Msg", "ConsistentHashKey", "TracingSpan", });
    internal_static_net_arksea_dsf_demo_DemoResponse1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_arksea_dsf_demo_DemoResponse1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_arksea_dsf_demo_DemoResponse1_descriptor,
        new java.lang.String[] { "Msg", "Status", "TracingSpan", });
    internal_static_net_arksea_dsf_demo_DataResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_arksea_dsf_demo_DataResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_arksea_dsf_demo_DataResult_descriptor,
        new java.lang.String[] { "Key", "Payload", "Serialize", "TypeName", "ExpiredTime", "ErrorCode", "TracingSpan", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
