@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 20

participant User
participant Client
participant RequestRouter

User -> Client: request
activate Client
Client ->> RequestRouter: ask(DSF.ServiceRequest)
activate RequestRouter
Client -->o Client: map(decodeResponse)
User <-- Client: Future
deactivate Client
RequestRouter -> RequestRouter : getInstance
RequestRouter -\\ ServiceAdaptor: DSF.ServiceRequest
deactivate RequestRouter
activate ServiceAdaptor
note right: ServiceRequest提供ConsistentHashable能力，\n用于ConsistentHashingPool类型\n的UserServiceActor实例池
ServiceAdaptor -\\ UserServiceActor: ServiceRequest
deactivate ServiceAdaptor
activate UserServiceActor
UserServiceActor -// ServiceAdaptor: ServiceResponse
deactivate UserServiceActor
activate ServiceAdaptor
ServiceAdaptor -// RequestRouter: DSF.ServiceResponse
deactivate ServiceAdaptor
activate RequestRouter
RequestRouter -//o Client: DSF.ServiceResponse
RequestRouter -> RequestRouter: onRequestSucceed
activate RequestRouter
deactivate RequestRouter
deactivate RequestRouter


@enduml